config/routes.rb
Rails.application.routes.draw do
  root to: 'novels#index'
  resources :novels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/novel.rb
class Novel < ApplicationRecord
  validates :title, :main_text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  
  def index
    @novels = Novel.all
  end

  def new
    @novel = Novel.new
  end

  def create
    Novel.create(novel_params)
    redirect_to '/'
  end

  def destroy
    novel = Novel.find(params[:id])
    novel.destroy
    redirect_to root_path
  end

  def edit
    @novel = Novel.find(params[:id])
  end

  def update
    novel = Novel.find(params[:id])
    novel.update(novel_params)
    redirect_to root_path
  end

  def show
    @novel = Novel.find(params[:id])
  end

  private
  def novel_params
    params.require(:novel).permit(:title, :main_text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NovelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>

    </header>
    <%= yield %>
  </body>
</html>

app/views/novels/edit.html.erb
<%= form_with(model: @novel, local: true, class: "novel-form") do |form|%>
  <div class="form-group">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
  </div>
  <div class="form-group">
    <%= form.label :main_text, "本文"%>
    <%= form.text_area :main_text,rows: "10" %>
  </div>
  <div class="form-group">
    <%= form.submit "保存" %>
  </div>
<% end %>
<%= link_to '小説一覧に戻る', novels_path %>

app/views/novels/index.html.erb
<%= link_to '新規作成', new_novel_path %>
<% @novels.each do |novel| %>
  <p><%= novel.title %></p>
  <%= link_to '閲覧', novel_path(novel.id)%>
  <%= link_to '編集', edit_novel_path(novel.id) %>
  <%= link_to '削除', novel_path(novel.id), data: { turbo_method: :delete } %>
<% end %>

app/views/novels/new.html.erb
<%= form_with(model: @novel, local: true, class: "novel-form") do |form|%>
  <div class="form-group">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
  </div>
  <div class="form-group">
    <%= form.label :main_text, "本文"%>
    <%= form.text_area :main_text,rows: "10" %>
  </div>
  <div class="form-group">
    <%= form.submit "保存" %>
  </div>
<% end %>

app/views/novels/show.html.erb
<p><%= @novel.title %></p>
<p><%= @novel.main_text %></p>
<%= link_to '小説一覧に戻る', novels_path %>